name: teb_mesada
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5+51

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0

  teb_package:
    #git:
    #  url: https://github.com/marcosmhs/teb_package.git
    #  ref: main
    path: ../teb_package
  
  intl: ^0.20.2
  flutter_localization: ^0.3.2
  google_fonts: ^6.2.1
     
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.2

  # firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.9

  # for image controller
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  image: ^4.5.4

  # for zip code API
  http: ^1.4.0  

flutter:

  uses-material-design: true

  assets:
    - assets/img/logo.png